project:
  type: book
  title: "The Dictionary Maker"
  output-dir: ../docs/en

book:
  title: "The Dictionary Maker"
  author: "Bude Sethaputra-Piccin"
  date: "2025-07-24"
  cover-image: "../_resources/assets/images/DictionaryMakerCover.jpeg"
  search: true
  downloads: [pdf, epub]
  chapters:
    - index.qmd
    - CH01-The_Last_Siamese.qmd
    - CH02-Siam_in_Transition.qmd
    - CH03-The_Elite_Under_Threat.qmd
    - CH04-The_Coup_and_Its_Aftermath.qmd
    - CH04_5-The_Net_Closes.qmd
    - CH05-Prison_University.qmd
    - CH06-The_Dictionary_Project_Begins.qmd
    - CH07-Rising_Storm.qmd
    - CH08-Tarutao_Exile.qmd
    - CH09-War_Comes_to_Siam.qmd
    - CH10-Survival_and_Perseverance.qmd
    - CH11-Liberation_and_Legacy.qmd
    - CH12-The_Dictionary_Makers_Gift.qmd
    - references.qmd

bibliography: references.bib
nocite: '@*'

format:
  html:
    theme: cosmo
    toc: true
    page-footer: "Copyright 2025 Bude Sethaputra-Piccin"
    site-url: "https://ensembio.github.io/sethaputra/"
  pdf:
    papersize: "Letter"
    mainfont: "Georgia"
    CJKmainfont: "STSong"  # or another CJK font you have installed
    toc: true
    documentclass: scrbook
    geometry: paperwidth=6in,paperheight=9in
    standalone: true
    toc-depth: 2  
    keep-tex: true
    include-in-header:
      - text: |
          \usepackage{xeCJK}
          \setCJKmainfont{STSong}
    header-includes:
      - \raggedbottom
  epub:
    toc: true
    cover-image: "../_resources/assets/images/DictionaryMakerCover.jpeg"