project:
  type: book
  title: "The Dictionary Maker"

book:
  title: "The Dictionary Maker"
  author: "Bude Piccin Sethaputra"
  date: "2025-07-24"
  search: true
  downloads: [pdf, epub]
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib
nocite: '@*'

format:
  html:
    theme: cosmo
    toc: true
    page-footer: "Copyright 2025 Bude Piccin"
    site-url: "https://ensembio.github.io/sethaputra/"
  pdf:
    papersize: "Letter"
    mainfont: "Georgia"
    CJKmainfont: "STSong"  # or another CJK font you have installed
    toc: true
    documentclass: scrbook
    geometry: paperwidth=6in,paperheight=9in
    standalone: true
    toc-depth: 2  
    keep-tex: true
    include-in-header:
      - text: |
          \usepackage{xeCJK}
          \setCJKmainfont{STSong}
    header-includes:
      - \raggedbottom